class NotebookGraphOutput:
    def __init__(self, graph):
        self.graph = graph

    def get_expanded_graph_dico(self, positions):
        dico = self.graph.get_expanded_dependency_graph_dico()
        self._require_positions(dico["nodes"], positions)

        nodes = []
        for node in dico["nodes"]:
            nodes.append(
                {
                    "id": node["id"],
                    "name": node["name"],
                    "position": self.scale_position(positions[node["id"]]),
                    "code": node["code"],
                }
            )

        edges = []
        for edge in dico["edges"]:
            edges.append(
                {
                    "A": edge["A"],
                    "B": edge["B"],
                    "color": edge.get("color", ""),
                    "condition": edge.get("condition", ""),
                    "id": f"{edge['A']} -> {edge['B']}",
                }
            )

        return {
            "nodes": nodes,
            "edges": edges,
            "subworkflows": self.get_final_subworkflows(dico["subworkflows"]),
        }

    def get_graph_dico(self, positions):
        self._require_positions(self.graph.nodes, positions)

        nodes = []
        for node in self.graph.nodes:
            nodes.append(
                {
                    "id": node["id"],
                    "name": node["name"],
                    "position": self.scale_position(positions[node["id"]]),
                    "code": node["code"],
                    "output": node["output"],
                }
            )

        edges = []
        for edge in self.graph.edges:
            edges.append(
                {
                    "A": edge["A"],
                    "B": edge["B"],
                    "color": "",
                    "condition": "",
                    "id": f"{edge['A']} -> {edge['B']}",
                }
            )

        return {
            "nodes": nodes,
            "edges": edges,
            "subworkflows": {},
        }

    def _require_positions(self, nodes, positions):
        if not positions:
            raise ValueError("Graphviz positions are required to build graph JSON.")

        missing_positions = [
            node["id"] for node in nodes if node["id"] not in positions
        ]
        if missing_positions:
            raise ValueError(
                f"Missing Graphviz positions for nodes: {', '.join(missing_positions)}"
            )

    def get_final_subworkflows(self, subflows):
        final = {}
        for sub_id in sorted(subflows):
            subflow = subflows[sub_id]
            final[sub_id] = {
                "nodes": list(subflow["nodes"]),
                "label": subflow["label"],
                "color": subflow["color"],
            }
        return final

    def scale_position(self, position):
        # Keep the node centres generated by Graphviz in the exported graph.
        return {
            "x": str(position["x"]),
            "y": str(position["y"]),
        }
